jQuery(function(){
  		$("#date_pickers_one").datepicker();
  		$("#date_pickers_two").datepicker();
  		$("#date_pickers_three").datepicker();
  		$("#date_pickers_four").datepicker();
		$("#date_pickers_five").datepicker();
		$("#date_pickers_six").datepicker();
		$("#date_pickers_seven").datepicker();
		$("#date_pickers_eight").datepicker();
		$("#date_pickers_onex").datepicker();
		$("#date_pickers_twox").datepicker();
   })
